version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - ffflorian
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "< 10.12"
    - "> 10.11.2"
  - dependency-name: "@types/node"
    versions:
    - "< 10.13"
    - "> 10.12.8"
  - dependency-name: "@types/node"
    versions:
    - "> 11.9.0"
    - "< 11.10"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a"
    - "< 14"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 0.3.21"
    - ">= 0.3.20.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 0.3.22"
    - ">= 0.3.21.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 0.3.23"
    - ">= 0.3.22.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 0.3.24"
    - ">= 0.3.23.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 0.3.27"
    - ">= 0.3.26.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 1.0.10"
    - ">= 1.0.9.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 1.0.17"
    - ">= 1.0.16.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 1.0.18"
    - ">= 1.0.17.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 1.0.19"
    - ">= 1.0.18.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 1.0.20"
    - ">= 1.0.19.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 1.0.4"
    - ">= 1.0.3.a"
  - dependency-name: "@wireapp/bot-api"
    versions:
    - "< 1.1"
    - "> 1.0.15"
