branch-defaults:
  master:
    environment: wire-hassmelden-bot
deploy:
  artifact: dist/wire-hassmelden-bot.zip
global:
  application_name: WireBots
  default_platform: Node.js
  default_region: eu-west-1
  profile: florian
  sc: git
  workspace_type: Application
