branch-defaults:
  master:
    environment: wire-echo-bot
deploy:
  artifact: dist/wire-echo-bot.zip
global:
  application_name: WireBots
  default_platform: Node.js
  default_region: eu-central-1
  profile: florian
  sc: git
  workspace_type: Application
